export const videoPosterImg = require('./video-poster.jpg')
export const offeringPosterImg = require('./offering-poster.jpg')
export const textBrand = require('./brand-text.png')
export const darkTextBrand = require('./brand-text-dark.png')
export const imgBrand = require('./favicon.png')